### PR TITLE
Create new DataBoundSetter in both file.

### PR DESCRIPTION
**Pull request by imaffe**
Summary of this pull request:
- [Added @DataBoundSetter annotation to both ExwsStep.java and ExwsAllocateStep.java ]
- [The test is not complete : no backward compatibility test yet ]
- [Just use this PR to see if the build can pass]

CC @martinda

### CODE REVIEW

**Comment by martinda** [comment]
Thanks for trying this @imaffe, and as you are probably seeing too, the test fails. I wish I had more time but at this point I am very busy with getting new GSoC proposals in order, on top of my regular full time job.

**Comment by imaffe** [comment]
Yeah it's OK, I will try get this fixed all by myself ! That's an interesting work to do ! You don't need to worry about this and I will take care of this ! Good luck and thanks for your work in GSoC :) @martinda

**Comment by martinda** [comment]
@imaffe I think it is best if you create a pull-request with the original project. If it comes through me, it will be delayed and will not get reviewed as fast.

**Comment by imaffe** [comment]
@martinda  yeah i was working on my PR with the original project since I found that would be the best practice. I'll close this PR, thank you Martin!

**Pull request closed without merging**
